home_automation_server/urls.py
from django.contrib import admin
from django.urls import path, include
from internet_of_things.views.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('devices/', include('internet_of_things.urls')),
    path('api/devices/', include('internet_of_things.api_urls'))
]

internet_of_things/urls.py
from django.urls import path
from internet_of_things.views import views as htmx_views

app_name = 'iot'

urlpatterns = [
    path('', htmx_views.devices_list, name='devices_list'),  # Render a list of devices
    path('create/', htmx_views.create_device, name='create_device'),  # HTMX form for creating a device
    path('<int:device_id>/', htmx_views.device_details, name='device_detail'),  # Device detail view
    path('<int:device_id>/log', htmx_views.device_logs, name='device_logs'),
]

internet_of_things/models.py
from django.db import models
from django.utils.timezone import now

LOG_DATA_TYPES = [
    ("string", "String"),
    ("int", "Int"),
    ("datetime", "Datetime"),
    ("float", "Float"),
    ("bool", "Bool")
]

class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Device(models.Model):
    name = models.CharField(max_length=255, unique=True)
    location = models.CharField(max_length=255, default=None, null=True, blank=True)
    device_type = models.CharField(max_length=255, default=None, null=True, blank=True)
    tags = models.ManyToManyField(Tag, default=None, blank=True)

    def __str__(self):
        return self.name

class DeviceLogField(models.Model):
    name = models.CharField(max_length=255)
    data_type = models.CharField(choices=LOG_DATA_TYPES, default="string", max_length=50)
    units = models.CharField(max_length=10, null=True, blank=True)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    sort_order = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.device.name} field - {self.name}"

class DeviceLog(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    log = models.JSONField()
    log_datetime = models.DateTimeField(default=now)

    def __str__(self):
        return f"{self.device.name} log - {self.log_datetime.strftime(format='%Y-%m-%d %H:%M:%S')}"

internet_of_things/forms.py
from django import forms
from internet_of_things.models import Tag

class DeviceForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter device name',
            'id': 'deviceName'
        })
    )
    location = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter location',
            'id': 'deviceLocation'
        })
    )
    device_type = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter device type',
            'id': 'deviceType'
        })
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        to_field_name="id",
        widget=forms.SelectMultiple(attrs={
            'class': 'form-control',
            'id': 'deviceTags'
        }),
        required=False,
    )

internet_of_things/views.py
from rest_framework.views import APIView

from internet_of_things.models import Device, DeviceLog
from rest_framework.response import Response
from rest_framework.decorators import api_view
from internet_of_things.serializer import DeviceSerializer, DeviceLogSerializer


@api_view(['GET'])
def get_devices(request):
    devices = Device.objects.all()
    serializer = DeviceSerializer(devices, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def get_device(request, device_id: int):
    device = Device.objects.get(id=device_id)
    serializer = DeviceSerializer(device, many=False)
    return Response(serializer.data)


class DeviceLogView(APIView):
    @staticmethod
    def get(request, device_id: int):
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
        device_logs = DeviceLog.objects.filter(device_id=device_id)
        if start_date:
            device_logs = device_logs.filter(log_datetime__gte=start_date)
        if end_date:
            device_logs = device_logs.filter(log_datetime__lte=end_date)
        serializer = DeviceLogSerializer(device_logs, many=True)
        return Response(serializer.data)

    @staticmethod
    def post(request, device_id: int):
        data = request.data
        device_log =  DeviceLog.objects.create(device_id=device_id, log=data)
        serializer = DeviceLogSerializer(device_log, many=False)
        return Response(serializer.data, status=201)

internet_of_things/views/api_views.py
from rest_framework.views import APIView
from internet_of_things.models import Device, DeviceLog
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.request import Request
from internet_of_things.serializer import DeviceSerializer, DeviceLogSerializer

@api_view(['GET'])
def api_get_devices(request: Request):
    devices = Device.objects.all()
    serializer = DeviceSerializer(devices, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def api_get_device(request: Request, device_id: int):
    device = Device.objects.get(id=device_id)
    serializer = DeviceSerializer(device, many=False)
    return Response(serializer.data)


class DeviceLogAPIView(APIView):
    @staticmethod
    def get(request: Request, device_id: int):
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
        device_logs = DeviceLog.objects.filter(device_id=device_id)
        if start_date:
            device_logs = device_logs.filter(log_datetime__gte=start_date)
        if end_date:
            device_logs = device_logs.filter(log_datetime__lte=end_date)
        serializer = DeviceLogSerializer(device_logs, many=True)
        return Response(serializer.data)

    @staticmethod
    def post(request: Request, device_id: int):
        print(type(request), "post request type")
        data = request.data
        device_log =  DeviceLog.objects.create(device_id=device_id, log=data)
        serializer = DeviceLogSerializer(device_log, many=False)
        return Response(serializer.data, status=201)

internet_of_things/views/views.py
import django.db.utils
from django.db import transaction
from internet_of_things.models import Device, DeviceLog, DeviceLogField
from django.shortcuts import render, redirect
from internet_of_things.forms import DeviceForm
from django.core.handlers.wsgi import WSGIRequest

def home(request: WSGIRequest):
    print(type(request))
    return render(request, 'home.html')

def devices_list(request: WSGIRequest):
    devices = Device.objects.all()
    context = {"devices": devices}
    return render(request, 'all_devices.html', context=context)

def device_details(request: WSGIRequest, device_id: int):
    device = Device.objects.get(id=device_id)
    context = {"device": device}
    return render(request, 'device_details.html', context=context)

def device_logs(request: WSGIRequest, device_id: int):
    logs = DeviceLog.objects.filter(device_id=device_id)
    log_fields = DeviceLogField.objects.filter(device_id=device_id).order_by('sort_order')
    context = {"logs": logs, "log_fields": log_fields}
    return render(request, 'device_logs.html', context=context)

def create_device(request: WSGIRequest):
    if request.method == 'GET':
        form = DeviceForm()
        return render(request, 'create_device.html', {'form': form})
    if request.method == 'POST':
        form = DeviceForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            location = form.cleaned_data['location']
            device_type = form.cleaned_data['device_type']
            tags = form.cleaned_data['tags']
            try:
                with transaction.atomic():
                    device = Device.objects.create(name=name, location=location, device_type=device_type)
                    device.save()
                    device.tags.set(tags)
                return redirect('home')
            except django.db.utils.IntegrityError:
                form.add_error('name', 'Device with this name already exists.')
        return render(request, 'create_device.html', {'form': form}, status=400)

templates/all_devices.html
<table class="table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Device Type</th>
    </tr>
    </thead>
    <tbody>
    {% for device in devices %}
        <tr onclick="window.location.href='/devices/{{ device.id }}'" style="cursor: pointer;">
            <td>{{ device.name }}</td>
            <td>{{ device.location|default:"-" }}</td>
            <td>{{ device.device_type|default:"-" }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django HTMX{% endblock %}</title>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/create_device.html
{% extends 'base.html' %}

{% block content %}
    <p>create device</p>
    <form action="{% url 'iot:create_device' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="deviceName" class="form-label">Device Name</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label for="deviceLocation" class="form-label">Location</label>
            {{ form.location }}
        </div>
        <div class="mb-3">
            <label for="deviceType" class="form-label">Device Type</label>
            {{ form.device_type }}
        </div>
        <div class="mb-3">
            <label for="deviceTags" class="form-label">Tags</label>
            {{ form.tags }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/device_details.html
{% extends 'base.html' %}

{% block title %}Device Details{% endblock %}


{% block content %}
    <div class="row">
        <h4>Device:{{ device.name }} </h4>
        <div class="col">
            <div class="d-block">
                <b>Location</b><p>{{ device.location }}</p>
                <b>Device Type</b><p>{{ device.device_type }}</p>
            </div>
            <div hx-get="/devices/{{ device.id }}/log" hx-trigger="load" hx-swap="innerHTML"></div>
        </div>
        <div class="col">
        </div>
    </div>
    
{% endblock %}

templates/device_logs.html
{% load custom_filters %}

<table class="table table-sm">
    <thead>
        {% for field in log_fields %}
            <th>{{ field.name|replace:"_, "|capitalize }}</th>
        {% endfor %}
        <th>Datetime</th>
    </thead>
    <tbody>
    {% for log in logs %}
        <tr>
            {% for field in log_fields %}
                <td>{{ log.log|dict_get:field.name }}</td>
            {% endfor %}
            <td>{{ log.log_datetime|date:"Y-m-d H:i:s" }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home Server{% endblock %}

{% block content %}
    <a href="{% url 'iot:create_device' %}" class="btn btn-primary">Create Device</a>
    <div class="row">
        <div class="col-6">
            <div hx-get="{% url 'iot:devices_list' %}" hx-swap="innerHTML" hx-trigger="load">
                Getting Devices....
            </div>
        </div>
        <div class="col-6"></div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Home Server{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div hx-get="{% url 'iot:devices_list' %}" hx-swap="innerHTML" hx-trigger="load">
                Getting Devices....
            </div>
        </div>
        <div class="col-6"></div>
    </div>
{% endblock %}